### ISSUE TITLE
Reference for IC50 data used

### ISSUE THREAD

**Issue by sonyahanson** [choderalab/dispensing-errors-manuscript#13]
Curious what the 'Fregau et al' reference is. Do we already have it in https://github.com/choderalab/dispensing-errors-manuscript/tree/master/references ? Is this one of the patents?

From ipython notebook:

<pre>
# data from Fig 1 of Fregau et al.
echo_IC50s = np.array([0.064, 0.486, 0.003, 0.002, 0.007, 0.003, 0.004, 0.052, 0.01362, 0.207, 0.158, 0.01164, 0.00633, 0.00358]) * 1e-6 # M
genesis_IC50s = np.array([0.817, 3.03, 0.146, 0.553, 0.973, 0.778, 0.445, 0.17, 0.112, 14.4, 0.25, 0.049, 0.087, 0.152]) * 1e-6 # M
</pre>

**Comment by jchodera** [comment]
Sorry----that should be the [Ekins et al PLoS One paper](http://dx.doi.org/10.1371/journal.pone.0062325).  See [Fig. 1](http://journals.plos.org/plosone/article/figure/image?size=medium&id=info:doi/10.1371/journal.pone.0062325.g001).

I don't know how I typed "Fregau".

**Comment by sonyahanson** [comment]
Ahhh! Thanks.
