### ISSUE TITLE
IC50 vs. Ki?

### ISSUE THREAD

**Issue by sonyahanson** [choderalab/dispensing-errors-manuscript#17]
Just wanted to double check. I'm not totally clear on how `scipy.optimize.curve_fit` works, but it seems like this function is actually fitting Ki and not IC50? 

<pre>
def fit_ic50(inhibitor_concentrations, activities):
    def objective(inhibitor_concentrations, Ki):
        activities = np.zeros([ndilutions], np.float64)
        for i in range(ndilutions):
            activities[i] = competitive_inhibition(substrate_concentration, inhibitor_concentrations[i], enzyme_concentration, Ki, Km)
        return activities
            
    Ki_guess = true_Ki
    import scipy.optimize
    [popt, pcov] = scipy.optimize.curve_fit(objective, inhibitor_concentrations, activities, p0=[Ki_guess])
    
    return popt[0]
</pre>

Let me know if I'm mistaken here. I would think to fit Ki we would actually want to use the equation `IC50 = Ki* (1 + substrate_concentration/Km)` somewhere.

I guess it is only different by a constant, so it is not a big deal, but i just want to make sure I'm not missing something.

**Comment by jchodera** [comment]
Good catch!  I was indeed fitting Ki and plotting pKi rather than pIC50.  

We can convert between the two via the relationship you suggest (assuming competitive binding), [as in this reference](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2703898/).

**Comment by jchodera** [comment]
Might as well implement this?

**Comment by sonyahanson** [comment]
Oh, sorry, just saw this. The new notebook is now a pull request! 

Can fix this in the next go, while fixing some of the other things mentioned in the PR.

**Comment by jchodera** [comment]
Sounds good.

**Comment by sonyahanson** [comment]
Hmmm. Somehow when I tried this, it seems to throw off the bias quite a bit. Any suggestions why just changing the function to `return (popt[0]* (1 + substrate_concentration/Km))` wouldn't be correct?

Also is it really returning Ki or would it be activity?
Wouldn't mind a bit of explanation of the use of `scipy.optimize.curve_fit`.

**Comment by bas-rustenburg** [comment]
Are all your units on those numbers consistent?

**Comment by bas-rustenburg** [comment]
Also, `scipy.optimize.curve_fit` takes an arbitrary function (f) with parameters (any extra keyword arguments are used as first guess) and your data. It then uses a non-linear least squares fit to estimate the most likely parameter values, so it assumes ydata = f(xdata, *params) + eps. 

See also the short example at the bottom of 
http://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.curve_fit.html

**Comment by jchodera** [comment]
Apologies that I don't have time to look at this in great detail until my flight tomorrow, but [here is a nice tutorial on using `scipy.optimize.curve_fit` to fit models to data](http://www2.mpia-hd.mpg.de/~robitaille/PY4SCI_SS_2014/_static/15.%20Fitting%20models%20to%20data.html)!

**Comment by bas-rustenburg** [comment]
@jchodera nice example!

 I'm actually not so sure about the first guess arguments, maybe I'm confusing it with another scipy function.

**Comment by jchodera** [comment]
If we have IC50 = Ki \* (1 + [S]/Km), then when we take the log, we should have 

pIC50 = pKi + constant

Where the constant depends on Km and substrate concentration.  So it is conceivable that it will affect the bias of pIC50 because it will shift everything by a constant, but it can only shift things toward INCREASING bias since log(1 + [S]/Km) must be positive.

**Comment by sonyahanson** [comment]
From @jchodera:

> Apologies that I don't have time to look at this in great detail until my flight tomorrow, but [here is a nice tutorial on using `scipy.optimize.curve_fit` to fit models to data](http://www2.mpia-hd.mpg.de/~robitaille/PY4SCI_SS_2014/_static/15.%20Fitting%20models%20to%20data.html)!

**Comment by sonyahanson** [comment]
This doesn't seem to have changed anything. I did change the fit to be fitting to IC50, instead of Ki, it is rather hacky.
