### ISSUE TITLE
Coordinate assay values in ipython notebook to values in patent methods?

### ISSUE THREAD

**Issue by sonyahanson** [choderalab/dispensing-errors-manuscript#19]
From @jchodera:

> I may be confused about where the data we're using came from.  Is it from [this patent](http://www.google.com/patents/US7718653)?  The section on assay (A)
> 
> ```
> EXAMPLE 13 Biological Assays
> A) In vitro EphB4 Enzyme Assay
> ```
> 
> says there was 0.25 ng of EphB4 in 10 uL assay buffer, which is an enzyme concentration of (MW 76.8 kDa), which gives (0.25e-9 g) / (76.8e3 g/mol) / (10e-6 L) = 32.5 nM kinase.  The notebook says 4 uM ATP, but 6 uM enzyme concentration.  Not sure if I misread that or took a wild guess or something.

**Comment by sonyahanson** [comment]
Okay, so just looked into this a little further. The Ekins dataset is 14 compounds: 8 are from the US patent 7,718,653 and 6 are from the US patent WO2009010794 A1 or US20090054428 (the second labeled as W). 

The biological assay in 7718653 (what you wrote above) is an assay that detects inhibitors of EphB4-mediated phosphorylation of polypeptide substrate using Alphascreen, where EphB4 is incubated with a biotinylated substrate in the presence of ATP, and after the reaction is stopped by EDTA and streptavidin-coated donor beads. The substrate is then incubated with anti-phosphotyrosine antibodies on acceptor beads. Inhibition is measured by a decrease in the signal intensity of emission at 520-620 nm upon excitation of the donor beads at 680 nm.

The dilution series using the genesis was created with 10 mM stock solutions in DMSO that were serially diluted with 5% DMSO. 2 uL of this 6x dilution series was added to 10 uL of the enzyme solution, to a total of 12 uL. With 0.25 ng recombinant, active EphB4 and 4 uM \* (10/12) = 3.33 uM ATP. This last bit is because it is 10 uL of assay mix at 4 uM ATP, but the final volume is 12 uL.

The dilution series using the echo was created with 100% DMSO stocks and dispensed in multiples of 2.5 nL droplets to a total of 120 nL DMSO in each well. The total volume here was also 12 uL with 0.25 ng recombinant, active EphB4 and 3.33 uM ATP.

The resulting signal was determined by the Perkin Elmer EnVision Plate Reader. Everything was done in low volume white 384-well assay plates (Greiner Cat No. 784075).

Both patents seem to have identical (even in wording) methods for this assay.

**Comment by jchodera** [comment]
Thanks!

Note that I used the undiluted concentrations for EphB and ATP in the
notebook because I had an explicit step to dilute those by adding 2 uL
compound solution to 10 uL assay mix.

**Comment by sonyahanson** [comment]
Seems like we're fine for this? I don't think I made any changes in the new notebook related to this issue.
