### ISSUE TITLE
Sliders in final ipython notebook?

### ISSUE THREAD

**Issue by sonyahanson** [choderalab/dispensing-errors-manuscript#20]
So I did a bit of playing with the IPython.html.widgets way of doing this, and didn't quite get to all the way there. I have the examples at the end of the notebok, in a new branch in my github: https://github.com/sonyahanson/dispensing-errors-manuscript/blob/playing_with_sliders/notebooks/New_Format_with_Slider.ipynb

We don't actually need this in the final companion notebook, I just already knew how to do it with ipywidgets, and thought it would be cool to add for the NYC Media Lab Summit demo. Which was awesome, btw.

**Comment by jchodera** [comment]
D'oh!  I meant to ask about that!

Can I get you to give a brief summary right before group meeting Weds?
