### ISSUE TITLE
Add dilution step for transferring 2 uL

### ISSUE THREAD

**Issue by sonyahanson** [choderalab/dispensing-errors-manuscript#24]
yup

**Comment by sonyahanson** [comment]
This worked! Will make pull request soon
![ic50_compare_w_bias](https://cloud.githubusercontent.com/assets/6333823/10295750/cea180d6-6b90-11e5-9d06-f36ba8dd0587.png)

**Comment by sonyahanson** [comment]
The larger shift is back! The only reason I'm not making this a pull request now, is because I think I also want to change the name of the ipynb to our final name, and I think I will leave the slider out of the main version for now. Thinking about naming them `errors_in_dipensing.ipynb` and `errors_in_dispensing-with_sliders.ipynb`. And delete the `Serial Dilution Accuracy.ipynb` notebook.

**Comment by jchodera** [comment]
> The larger shift is back!

Hooray!  And we learned something about what the main contributors to the shift actually are.

> The only reason I'm not making this a pull request now, is because I think I also want to change the name of the ipynb to our final name,

What about committing this and changing the name in a separate PR?

> Thinking about naming them errors_in_dipensing.ipynb and errors_in_dispensing-with_sliders.ipynb. And delete the Serial Dilution Accuracy.ipynb notebook.

Why the weird combination of _ and -?

**Comment by jchodera** [comment]
What about `echo-vs-tips.ipynb`?

**Comment by sonyahanson** [comment]
love it
