### ISSUE TITLE
Missing figures/placeholder.pdf

### ISSUE THREAD

**Issue by jchodera** [choderalab/dispensing-errors-manuscript#26]
Can you check in `figures/placeholder.pdf`?

```
    \includegraphics[width=1.0\textwidth]{../figures/placeholder.pdf}
```

It seems this was accidentally missed from the `figures/` directory.

Might be good to `git add figures/*`?

**Comment by sonyahanson** [comment]
closing this as we now have the real figure in there

**Comment by jchodera** [comment]
Did you like my placeholder version?
