### ISSUE TITLE
Adding missing references.

### ISSUE THREAD

**Issue by sonyahanson** [choderalab/dispensing-errors-manuscript#30]
What do these refer to, are they already in the Zotero library?

<pre>
 imprecise compound dispensing {\color{red}[CITE?]}, 
 unmonitored water absorption by DMSO stocks {\color{red}[CITE?]},
</pre>

**Comment by jchodera** [comment]
They were just a note to myself to try to fins something appropriate.

**Comment by sonyahanson** [comment]
Okay.

**Comment by sonyahanson** [comment]
Got the patents added to the zotero library in the correct format. Was pretty easy once I installed the zotero connector chrome plugin and just went to the google patents page.

**Comment by sonyahanson** [comment]
Also here are the JCAMD reference formatting instructions:

<pre>
*Citation*
Reference citations in the text should be identified by numbers in square brackets. Some examples:
1. Negotiation research spans many disciplines [3].
2. This result was later contradicted by Becker and Seligman [5].
3. This effect has been widely studied [1-3, 7].
*Reference list*
The list of references should only include works that are cited in the text and that have been published or accepted for publication. Personal communications and unpublished works should only be mentioned in the text. Do not use footnotes or endnotes as a substitute for a reference list.
The entries in the list should be numbered consecutively.
*Journal article*
Nugen S, Baeumner HJ (2008) Trends and opportunities in food pathogen detection. Anal Bioanal Chem 391:451-454
or
Nugen S, Baeumner HJ (2008) Anal Bioanal Chem 391:451-454
*Article by DOI*
Slifka MK, Whitton JL (2000) Clinical implications of dysregulated cytokine production. J Mol Med. Doi:10.1007/s001090000086
*Book*
South J, Blass B (2001) The future of modern genomics. Blackwell, London
Book chapter
Brown B, Aaron M (2001) In: Smith J (ed) The rise of modern genomics, 3rd edn. Wiley, New York
*Online document*
Healthwise Knowledgebase (1998) US Pharmacopeia, Rockville. http://www.healthwise.org. Accessed 21 Sept 1998
Always use the standard abbreviation of a journal’s name according to the ISSN List of Title Word Abbreviations, see
ISSN.org LTWA
If you are unsure, please use the full journal title.
For authors using EndNote, Springer provides an output style that supports the formatting of in-text citations and reference list.
EndNote style (zip, 2 kB)
</pre>

You can find these [here](http://www.springer.com/chemistry/physical+chemistry/journal/10822) in the 'Instructions for Authors' tab on the right.

**Comment by sonyahanson** [comment]
Chrome/Zotero/Mac seem to not work so great together. Switching to FireFox for the blog posts.
