### ISSUE TITLE
Fix acoustic-vs-tips.pdf

### ISSUE THREAD

**Issue by jchodera** [choderalab/dispensing-errors-manuscript#35]
`acoustic-vs-tips.pdf` keeps crashing my LaTeX editor and Preview---I think because too many bootstrap traces are plotted.  If we slice the bootstrap traces in the `plot` commands to only show every 10th trace, I think that will fix this!

**Comment by sonyahanson** [comment]
Think I've done this in pull request #36 , let me know if this fixes the problem.

**Comment by sonyahanson** [comment]
To be closed if the problem has indeed been resolved.

**Comment by jchodera** [comment]
It's much better!   My poor little mac still spins the beachball of death for a little while, but at least it works!
