### ISSUE TITLE
Make a figure 7 that shows no bias, bias without dilution, and bias with dilution

### ISSUE THREAD

**Issue by sonyahanson** [choderalab/dispensing-errors-manuscript#38]
Because of the way the variables are still really gross this is harder than you would think.

For now just sticking with no bias, and bias with dilution. Also would be nice to be sure about #37 when we do this.

**Comment by sonyahanson** [comment]
Did this:

![separating-bias](https://cloud.githubusercontent.com/assets/6333823/10888805/3a113128-815c-11e5-9060-60116f1845c4.png)

**Comment by sonyahanson** [comment]
Feel like this might be confusing to the reader...

**Comment by sonyahanson** [comment]
Maybe if #37 turns out not be an issue. We should make a figure showing the difference in bias w/ and w/out the transfer operation. Since right now this is not expounded upon very much in the paper, and does seem to be where most of the bias is coming from...

**Comment by sonyahanson** [comment]
There is now an extra notebook that does this in pull request #40 .

**Comment by jchodera** [comment]
I think this looks great to me, actually.  The only thing I might change is
- use different symbols (and maybe a mix of closed/open) for the colorblind
- connect the same measurements with thin or dotted lines?
