### ISSUE TITLE
Discard changes in newest echo-vs-tips-extras.ipynb?

### ISSUE THREAD

**Issue by sonyahanson** [choderalab/dispensing-errors-manuscript#44]
It does look like there were some changes made to this `ipynb`, on Saturday, I'm assuming I can disregard them in favor the changes made to `echo-vs-tips.ipynb`.
![wow](https://cloud.githubusercontent.com/assets/6333823/11042277/2eb8ac10-86e4-11e5-9b04-c910573bbebd.png)

**Comment by jchodera** [comment]
That was just me copying the notebooks on your "fixed" directory over the old ones.

**Comment by sonyahanson** [comment]
Okay.
