### ISSUE TITLE
Abstract typo?

### ISSUE THREAD

**Issue by sonyahanson** [choderalab/dispensing-errors-manuscript#5]
I'm making this an issue, partly because it's funny.

Current version of this sentence:

> To illustrate these techniques, we review an **hour** example of how choice of dispensing technology can greatly impact assay measurements, and show how the primary contributions to discrepancies between assay results can be easily understood.

In previous versions of this sentence the word was either **infamous** or **classic**.

I think 'hour' is a typo of some sort??

**Comment by jchodera** [comment]
I believe it should be _infamous_!  I don't know how that happened, though my guess is that I must have been typing when somebody walked into the room and then foolishly tried to talk and type at the same time.
