### ISSUE TITLE
Address Reviewer #1's comments on Figure 7

### ISSUE THREAD

**Issue by sonyahanson** [choderalab/dispensing-errors-manuscript#50]
> 1) The "original" series cannot be seen- I assume they are completely obscured by the other two series, i.e. probably the disposable tip series since these are assume to have little or no bias. 

In the version of this plot that I'm seeing the original are red points on top of the other points. Was the version they were looking at in black and white? What is a good way to fix this?

> 2) I'd initially assumed that each point should have both vertical _and_ horizontal error bars. However, when I realized that the fixed tips with dilution would not overlay because they are bias-corrected it seemed to me that _at least_ the different series ought to have _either_ horizontal error bars _or_ vertical bars, representing the imprecision of each. For all of them to have just horizontal error bars suggests that there is no imprecision in the "y", i.e. pIC50 (tips) direction. If there are in fact y-error bars but they are too small to be visualized this also at least should be mentioned.

My response to this would be that 'there are in fact y-error bars but they are too small to be visualized' and that we need to just mention this more clearly in the caption.

> 3) The authors show that more dilution wells increase the bias- which would alter figure 7, yet choose not to replicate this figure with this increased bias- which would be illustrative of the potentials of this approach, rather they add it to a separate figure 8. How much better to add a Figure 7b or to put these increased bias estimates on the same graph.

This won't be too hard. I'm leaning toward a 7B, as putting all this on one figure 7 might get a bit crowded.

**Comment by jchodera** [comment]
> My response to this would be that 'there are in fact y-error bars but they are too small to be visualized' and that we need to just mention this more clearly in the caption.

What if we make the points smaller so these can be seen?  I had tried to do this in one of my versions of that figure.

> This won't be too hard. I'm leaning toward a 7B, as putting all this on one figure 7 might get a bit crowded.

7B is a good idea.

**Comment by sonyahanson** [comment]
Is this better?
![better](https://cloud.githubusercontent.com/assets/6333823/11383169/642c04a4-92d4-11e5-986f-5de2737bf7de.png)

I'm still not really sure how they didn't see the 'original' point on the plot. I feel like there must be some color issue that we don't see in our versions of the figures.

**Comment by sonyahanson** [comment]
And proposal for figure 7B:

![um](https://cloud.githubusercontent.com/assets/6333823/11384242/50043836-92dc-11e5-97d3-9aa0f108567b.png)

Using:
`dilute_genesis_bias_interpolation_16 = interp1d(pKis, dilute_bias_16);`
`dilute_genesis_bias_interpolation_32 = interp1d(pKis, dilute_bias_32);`

These figures are also in recent pull request's `echo-vs-tips-extras-WIP.ipynb`

**Comment by jchodera** [comment]
Doesn't 7B omit, like, 25% of the data points?

**Comment by sonyahanson** [comment]
This is the area of the plot the zoom is representing (dark grey):

![see](https://cloud.githubusercontent.com/assets/6333823/11411287/bb49af34-939c-11e5-9fcf-6b6709b0df41.png)

**Comment by sonyahanson** [comment]
It's sort of blowing my mind that the order of the 8-16-32 well bias is different depending whether the original point is at (-8.2, -6) 
![first](https://cloud.githubusercontent.com/assets/6333823/11411510/9420c814-939e-11e5-82c9-a077b54852e3.png)
or (-8,-7.4).
![second](https://cloud.githubusercontent.com/assets/6333823/11411514/99d384f4-939e-11e5-9412-425c0fcbb8bf.png)

Though now I see our original figure 8 does show this too, especially when you consider the range we are looking at is still (-7.75, -5.75), which is right where that flip happens:
![dilute-bias-pic50-8-16-32](https://cloud.githubusercontent.com/assets/6333823/11411528/bff0deac-939e-11e5-9d57-2c14b4b13175.jpg)

**Comment by bas-rustenburg** [comment]
If you're dealing with overlapping points, how about setting the alpha for the points lower? 

Alternatively, you could add a slight jitter to the points so they're slightly offset without affecting the value too much. http://stackoverflow.com/questions/8671808/matplotlib-preventing-overlaying-datapoints

Edit: Or use different shapes that don't completely overlap.

**Comment by jchodera** [comment]
> This is the area of the plot the zoom is representing (dark grey):

Ah!  Maybe we should lightly shade that square region in light grey to make it obvious that the close-up looks at that region only?

> It's sort of blowing my mind that the order of the 8-16-32 well bias is different depending whether the original point is at (-8.2, -6) 

Far out, man.  Far.  Out.

**Comment by jchodera** [comment]
Jitter: no.

Alpha: good idea!  Worth trying?

**Comment by sonyahanson** [comment]
So here are the three new figures after incorporating these suggestions. Fig 7, and Fig 8A and 8B:

![newfig7](https://cloud.githubusercontent.com/assets/6333823/11480594/41fa4dc8-9766-11e5-90f2-ba519388d561.png)
![newfig8a](https://cloud.githubusercontent.com/assets/6333823/11480598/43bac732-9766-11e5-89b0-a3090f520efc.png)
![newfig8b](https://cloud.githubusercontent.com/assets/6333823/11480601/455bf2b4-9766-11e5-8248-f3cbd4a80996.png)

I can start adding these into the text now.
The only caption I'll need to change is that of Fig. 8, and a new mention of what the box is in Fig 7?

Do we want to add anything more to the text, for example a discussion of the switch of the order of magnitude of the bias for 8, 16, and 32 tips around pKi of -7?

**Comment by sonyahanson** [comment]
Actually, adjusted colors a bit to match, and probably going to set this as 8A:
![newfig8a-new](https://cloud.githubusercontent.com/assets/6333823/11481241/3f7386f6-976a-11e5-93ca-2bf851c6ec0a.png)

**Comment by sonyahanson** [comment]
Also, wondering if we are being sloppy about the pKi vs. pIC50 trends with this interpolation... Maybe a hangover from when we were still doing pKi calculations but calling them pIC50's...

**Comment by jchodera** [comment]
> Also, wondering if we are being sloppy about the pKi vs. pIC50 trends with this interpolation... Maybe a hangover from when we were still doing pKi calculations but calling the pIC50's...

Shoot, I had missed that.  I thought that this plot was plotting the bias in the measured pIC50 as a function of the true compound affinity and didn't see a problem with it, but I agree it might be easier to read if we plotted as a function of "true pIC50"?

**Comment by sonyahanson** [comment]
I'm going to look into this real quick.

**Comment by sonyahanson** [comment]
So this is how we're doing this:

<pre>
#define arbitrary pKi array
pKis = np.array([-12, -11, -10, -9, -8, -7, -6, -5, -4, -3], np.float64);
Kis = 10**pKis
nKis = len(pKis)
#initialize with zeros
genesis_pIC50_bias = np.zeros([nKis], np.float64)
genesis_pIC50_CV = np.zeros([nKis], np.float64)
for (i, Ki) in enumerate(Kis):
    IC50s = robot_IC50s(Ki)    
    pIC50s = np.log10(IC50s)
    pIC50_true = np.log10(Kis[i]*(1 + substrate_concentration/Km))
    genesis_pIC50_bias[i] = pIC50s.mean() - pIC50_true;
    genesis_pIC50_CV[i] = pIC50s.std() / abs(pIC50s.mean())   
</pre>

Then plotting

<pre>
# Plot relative error in measured Ki values as a function of true Ki.
plt.plot([pKis.min(), pKis.max()], [0, 0], 'k-', pKis, genesis_pIC50_bias, 'ro');
plt.xlabel('pKi');
plt.ylabel('bias in measured pIC50');
plt.axis([pKis.min()-0.5, pKis.max()+0.5, -1.5,1.5]);
</pre>

Should we actually be plotting this as a function of piC50s?

**Comment by sonyahanson** [comment]
I don't think this is wrong, though...

**Comment by sonyahanson** [comment]
Now the question is when we plot Figure 7, are we making the right conversion back to pIC50's. That is to say is there anything wrong with doing this:

<pre>
# Interpolate bias and CV for Echo and Genesis.
echo_bias_interpolation = interp1d(pKis, echo_pIC50_bias);
echo_CV_interpolation = interp1d(pKis, echo_pIC50_CV);
genesis_bias_interpolation = interp1d(pKis, genesis_pIC50_bias);
genesis_CV_interpolation = interp1d(pKis, genesis_pIC50_CV);
dilute_genesis_bias_interpolation = interp1d(pKis, dilute_genesis_pIC50_bias);
dilute_genesis_CV_interpolation = interp1d(pKis, dilute_genesis_pIC50_CV);
# Compute error bars for Echo and Genesis.
echo_pIC50_err = (echo_CV_interpolation(echo_pIC50s)*np.abs(echo_pIC50s))
genesis_pIC50_err = (genesis_CV_interpolation(genesis_pIC50s)*np.abs(genesis_pIC50s))
dilute_genesis_pIC50_err = (dilute_genesis_CV_interpolation(genesis_pIC50s)*np.abs(genesis_pIC50s))
</pre>

And we are plotting this:

<pre>
errorbar(echo_pIC50s, genesis_pIC50s, xerr=2*echo_pIC50_err, yerr=2*dilute_genesis_pIC50_err, fmt='ro', markersize=5, zorder=5);
</pre>

**Comment by sonyahanson** [comment]
I think this is still fine!

**Comment by sonyahanson** [comment]
Sorry for kind of thinking out loud here. Let me know if you disagree.

**Comment by jchodera** [comment]
AH.  I see your point now.  Will swing by your desk.

**Comment by jchodera** [comment]
OK, I think my assumption here was that the bias as a function of pIC50 was a pretty slowly changing function, so that we could use the bias as a function of measured pIC50 as an estimate of the true bias, and correct that way.

To do better than this, we would need to instead interpolate the bias as a function of measured pIC50 by creating the function for (pIC50 + bias), and then use that instead.  That should be a simple change, like

``` python
genesis_CV_interpolation = interp1d(compute_pIC50_from_pKi(pKis) + genesis_pIC50_CV, genesis_pIC50_CV);
```

where `compute_pIC50_from_pKi(pKi)` is a function that computes the pIC50 from pKI.

I think either approach is OK, with the second one being slightly better.  We will just want to document what we have done.

**Comment by sonyahanson** [comment]
This does change things slightly:

<pre>
# Doing the pIC50 interpolation correctly using function:
def compute_pIC50_from_pKi(pKis):
    Kis = 10**pKis
    return np.log10(Kis*(1 + substrate_concentration/Km))
# Interpolate bias and CV for Echo and Genesis.
echo_bias_interpolation = interp1d(compute_pIC50_from_pKi(pKis) + echo_pIC50_bias, echo_pIC50_bias);
echo_CV_interpolation = interp1d(compute_pIC50_from_pKi(pKis) + echo_pIC50_CV, echo_pIC50_CV);
genesis_bias_interpolation = interp1d(compute_pIC50_from_pKi(pKis) + genesis_pIC50_bias, genesis_pIC50_bias);
genesis_CV_interpolation = interp1d(compute_pIC50_from_pKi(pKis) + genesis_pIC50_CV, genesis_pIC50_CV);
dilute_genesis_bias_interpolation = interp1d(compute_pIC50_from_pKi(pKis) + dilute_genesis_pIC50_bias, dilute_genesis_pIC50_bias);
dilute_genesis_CV_interpolation = interp1d(compute_pIC50_from_pKi(pKis) + dilute_genesis_pIC50_CV, dilute_genesis_pIC50_CV);
</pre>

New RMSE shift is from 1.56 to 1.38 (was 1.40!). And these are the two new plots:

![new7](https://cloud.githubusercontent.com/assets/6333823/11485533/aeffec8c-9781-11e5-8a9b-069dd830775b.png)
![new8](https://cloud.githubusercontent.com/assets/6333823/11485535/b11f6858-9781-11e5-970b-9bc8511a7ba1.png)

Really small change. But the order of the increase in bias as we change the dilution series from 8 to 16 to 32 wells is the same.

**Comment by sonyahanson** [comment]
And likewise:

<pre>
dilute_genesis_bias_interpolation_16 = interp1d(compute_pIC50_from_pKi(pKis) + dilute_bias_16, dilute_bias_16);
dilute_genesis_bias_interpolation_32 = interp1d(compute_pIC50_from_pKi(pKis) + dilute_bias_32, dilute_bias_32);
</pre>

Looks like the 16 and 32 wells overlap exactly now.
