### ISSUE TITLE
Address Reviewer #2's request for HTML version of iPython notebook

### ISSUE THREAD

**Issue by sonyahanson** [choderalab/dispensing-errors-manuscript#51]
> Apparently, the authors aim to include the iPython notebooks as Supplementary Material, which is a brilliant idea! Besides the native ipynb format, it would be great to also provide the HTML form of the notebooks in the Supplementary. Of course, the HTML version is also available via the github repository or http://nbviewer.ipython.org. But there may readers out there who just want to go with the JCAMD material. For this audience, the HTML version of the notebooks would a benefit!

According to [this](https://ipython.org/ipython-doc/1/interactive/nbconvert.html) seems like this should be pretty straightforward, and we can include this html file as a more traditional form of supplemental material that the reader can download, in addition to having a link to the github repository. I assume that is what this means.

**Comment by jchodera** [comment]
The `--to html --template full` sounds great.

**Comment by jchodera** [comment]
It's probably worth seeing if we can also convert to some other formats that would be useful.  The PDF may also be convenient for viewing for some folks, and having a pure Python script would also be useful for some.

**Comment by jchodera** [comment]
Hell, even the `Reveal.js` slides could be cool.

**Comment by sonyahanson** [comment]
Did this! 
`ipython nbconvert echo-vs-tips.ipynb --to slides` and `ipython nbconvert echo-vs-tips.ipynb --to html` worked fine. They look very similar.

Also tried `ipython nbconvert echo-vs-tips.ipynb --to pdf` but had to install this thing called pandoc (`conda install -c https://conda.binstar.org/asmeurer pandoc`) and define the `TEXINPUTS` path so that it could see the images, and then I still got an error: `! I can't find file 'notebook.tex.'.` I feel like this is still a work in progress. Here is the trail of ipython/jupyter issues I followed, possible I am misunderstanding what is going on here: 
https://github.com/ipython/ipython/issues/8913
https://github.com/jupyter/nbconvert/issues/142
https://github.com/jupyter/nbconvert/pull/140
https://github.com/jupyter/nbconvert/pull/132

**Comment by sonyahanson** [comment]
I agree it would be nice to have a pdf version. Suggestions welcome.

**Comment by jchodera** [comment]
OK, letting users print out the HTML version is probably as good as we're going to get without significantly more effort.  So let's leave it at that.

**Comment by sonyahanson** [comment]
Okay. The slides version has been removed.
