### ISSUE TITLE
Figure 1 - Do we need permission to use Instrument Images?

### ISSUE THREAD

**Issue by sonyahanson** [choderalab/dispensing-errors-manuscript#53]
I got these from the respective websites for these instruments. They are slightly artified, but I'm not sure exactly how permissions work here.

![justchecking](https://cloud.githubusercontent.com/assets/6333823/11384527/81887924-92de-11e5-9236-711597c9bb6c.png)

**Comment by jchodera** [comment]
I believe our use of these image meets all four factors in the "four factor test" for Fair Use suggested by the MIT Libraries:
http://libguides.mit.edu/usingimages
